starterGrill_Jiacheng/config/routes.rb
Aya::Application.routes.draw do
  root to: "pages#show"

  resources :foods
  resources :users
  resources :reservations

  get '/menu' => 'foods#menu', as: 'menu'
  get '/location' => 'locations#show', as:'location'
  get '/sessions/new' => 'sessions#new', as: 'new_session'
  post '/sessions' => 'sessions#create', as: 'sessions'
  delete '/sessions' => 'sessions#destroy', as: 'session'
  get '/pages' => 'pages#show', as: 'login'
  get '/help' => 'pages#help', as:'help'


end

starterGrill_Jiacheng/app/models/reservation.rb
class Reservation < ActiveRecord::Base
  attr_accessible :date, :guest_number, :user_id
  belongs_to :user
  before_create :increase_points
  before_create :send_email
  after_destroy :decrease_points
  def increase_points
    user = User.find(self.user_id)
  	point = user.loyaltyPoint + 10
    user.update_column(:loyaltyPoint, point)

  end

  def decrease_points
    user = User.find(self.user_id)
    point = user.loyaltyPoint - 10
    user.update_column(:loyaltyPoint, point)

  end

  def send_email
  	user = User.find(self.user_id)
  	UserMailer.reservation_confirm_email(user).deliver
  end

end

starterGrill_Jiacheng/app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  # GET /reservations
  # GET /reservations.json


  before_filter :authorize_user, only: [:edit, :update, :destroy]

  def authorize_user
    reservation = Reservation.find(params[:id])
    if reservation.user != current_user
      redirect_to reservations_url, notice: "You can not edit or delete other users' reservation."
    end
  end


  def index
    @reservations = Reservation.where('date BETWEEN ? AND ?', DateTime.now.beginning_of_day, DateTime.now.end_of_day).all


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reservations }
    end
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
    @reservation = Reservation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reservation }
    end
  end

  # GET /reservations/new
  # GET /reservations/new.json
  def new
    @reservation = Reservation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reservation }
    end
  end

  # GET /reservations/1/edit
  def edit
    @reservation = Reservation.find(params[:id])
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(params[:reservation])
    @reservation.user_id = current_user.id
    @reservation.save

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to user_url(current_user), notice: 'Reservation was successfully created.' }
        format.json { render json: @reservation, status: :created, location: @reservation }
      else
        format.html { render action: "new" }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reservations/1
  # PUT /reservations/1.json
  def update
    @reservation = Reservation.find(params[:id])

    respond_to do |format|
      if @reservation.update_attributes(params[:reservation])
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy

    respond_to do |format|
      format.html { redirect_to reservations_url }
      format.json { head :no_content }
    end
  end
end

starterGrill_Jiacheng/app/helpers/reservations_helper.rb
module ReservationsHelper
end

starterGrill_Jiacheng/app/views/reservations/_form.html.erb
<%= form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>

  </div>
  <div class="field">
    <%= f.label :guest_number %><br />
    <%= f.number_field :guest_number,:in => 2...21 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

starterGrill_Jiacheng/app/views/reservations/edit.html.erb
<h1>Editing reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation, class: 'btn' %> |
<%= link_to 'Back', reservations_path, class: 'btn' %>

starterGrill_Jiacheng/app/views/reservations/index.html.erb
<% if(admin?) %>
<h1>Listing reservations</h1>
  <table class="table table-striped table-hover">
    <tr>
      <th>User</th>
      <th>Date</th>
      <th>Guest number</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

  <% @reservations.each do |reservation| %>
    <% user = User.find(reservation.user_id) %>
    <tr>
      <td><%= link_to user.name,user_url(user) %></td>
      <td><%= reservation.date %></td>
      <td><%= reservation.guest_number %></td>
      <td><%= link_to 'Show', reservation %></td>
      <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
      <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </table>

<br />

<%else%>
  <h1>Welcome to reservations</h1>
  <%= link_to 'New Reservation', new_reservation_path, class: 'btn' %>
<%end%>

starterGrill_Jiacheng/app/views/reservations/new.html.erb
<h1>New reservation</h1>

<% if signed_in? %>
<%= render 'form' %>
<% else %>
<h2> You did not sign in yet, so you can not make a reservation! </h2>
<% end %>

<%= link_to 'Back', login_path, class: 'btn' %>

starterGrill_Jiacheng/app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @reservation.user.name %>
</p>

<p>
  <b>Date:</b>
  <%= @reservation.date %>
</p>

<p>
  <b>Guest number:</b>
  <%= @reservation.guest_number %>
</p>


<%= link_to 'Edit', edit_reservation_path(@reservation), class: 'btn' %> |
<%= link_to 'Back', reservations_path, class: 'btn' %>