FinalProject/config/routes.rb
FinalProject::Application.routes.draw do




  root to: "pages#login"

  resources :follow_boards
  resources :likes
  resources :follows

  resources :pins do
    resources :comments
  end

  resources :boards
  resources :categories
  resources :users do
  	resources :boards
  	resources :pins
  end



  get '/sessions/new' => 'sessions#new', as: 'new_session'
  post '/sessions' => 'sessions#create', as: 'sessions'
  delete '/sessions' => 'sessions#destroy', as: 'session'
  get 'users/:id/addfriends' => 'users#add_friends', as: 'addfriends'
  get 'users/:id/addpin' => 'users#add_pin', as: 'addpin'
  get 'login' => 'pages#login', as: 'login'
  get 'users/:id/homefeed' => 'users#home_feed', as: 'homefeed'

end

FinalProject/app/models/user.rb
class User < ActiveRecord::Base

  after_update :send_pasword_changing_notification
  after_create :send_welcome_email
  before_destroy :send_destroy_survey_email
  attr_accessible :email, :gender, :name, :password, :password_confirmation

  has_many :boards, :dependent => :destroy
  has_many :pins, :dependent => :destroy
  has_many :follows, :dependent => :destroy
  has_many :followers, :through => :follows, :dependent => :destroy
  has_many :inverse_follows,  :class_name => "Follow", :foreign_key => "follower_id", :dependent => :destroy
  has_many :inverse_followers, :through => :inverse_follows, :source => :user, :dependent => :destroy
  has_many :likes, :dependent => :destroy
  has_many :follow_boards, :dependent => :destroy
  
  validates :name, :email, :password, :presence => true
  validates :email, :uniqueness => true

  has_secure_password

  def send_pasword_changing_notification
      if self.password_digest_changed?
        UserMailer.password_changing_notification(self).deliver
      end
  end

  def send_welcome_email
    UserMailer.welcome_email(self).deliver
  end

  def send_destroy_survey_email
    UserMailer.user_survey(self).deliver
  end


end

FinalProject/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize_user, :only => [:edit, :update, :destroy]

  def authorize_user
    @user = User.find(params[:id])
    if @user.id != session[:user_id]
      redirect_to users_path, notice: "Nice Try"
    end
  end

  def add_pin
    @pin = Pin.new
    @pinid = params[:pin_id]
    respond_to do |format|
      format.html # add_pin.html.erb
      format.json { render json: @users }
    end
  end

  def add_friends
    @users = User.all

    respond_to do |format|
      format.html # add_friends.html.erb
      format.json { render json: @users }
    end
  end



  def home_feed
    if signed_in?
      @boards =  current_user.boards
      @pins = current_user.pins

      @follow_boards = current_user.follow_boards
      @friends = current_user.follows
    end
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    if signed_in?
      @boards =  @user.boards
      @pins = @user.pins
      @follow_boards = @user.follow_boards
      @likes = @user.likes
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to login_url, notice: 'User was successfully created.' }
        format.json { render json: login_url, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    reset_session
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

FinalProject/app/helpers/users_helper.rb
module UsersHelper
end

FinalProject/app/views/users/_addpinform.html.erb
<%= form_for(@pin) do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.hidden_field :source, :value => Pin.find(@pinid).source %>
  </div>

  <div class="field">
    <%= f.label :board_id %><br />
    <%= f.collection_select :board_id, current_user.boards, :id, :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

FinalProject/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :gender %><br />
    <%= f.text_field :gender %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

FinalProject/app/views/users/add_friends.html.erb
<h1>Listing users</h1>

<table class="table table-striped table-hover">
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <%if user.id != current_user.id%>
    <tr>
      <td><%= user.name %></td>
      <td><%= link_to 'Show', user , class: 'btn btn-primary'%></td>
      <td><%= link_to "Add Friend", follows_path(:follower_id => user), class: 'btn btn-success', :method => :post %> </td>
    </tr>
    <%end%>
<% end %>
</table>

FinalProject/app/views/users/add_pin.html.erb
<h1>Pin it</h1>

<%if signed_in? %>
  <% if current_user.boards.present? %>
      <%= render 'addpinform' %>
      <%= link_to 'Back', user_path(current_user) %>
  <% else %>
      <p>There is no board in your account, you should create one first, redirecting........</p>
      <meta http-equiv="refresh" content="3;url=<%=new_board_path%>">
  <% end%>
<% else %>
  You are not signed in yet!
<% end %>

FinalProject/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

FinalProject/app/views/users/home_feed.html.erb
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script src="/path/to/jquery.masonry.min.js"></script>

<p>   <%= link_to "your personal profile" ,user_path(current_user.id), class: 'btn' %> </p>

<div id="container">
<ul>
      <% @follow_boards.each do |b| %>
      	<% b.board.pins.each do |p| %>
                  <div class="item">
      	     <%= link_to(image_tag('pin.png'),addpin_path(:pin_id=>p.id))
                                    %>

                  <%= link_to(image_tag('like.png'),likes_path(:like=>{"pin_id"=>p.id}), :method => :post)
                                    %>
                  <%= image_tag p.source%>
                  <%=p.description%>
                  </div>
      	<% end %>
      <% end %>

      <% if @friends.present? %>
            <% @friends.each do |f| %>
                  <% user = User.find_by_id(f.follower_id) %>
                  <% user.boards.each do |b| %>
                        <% b.pins.each do |p| %>
                        <div class="item">
                              <%= link_to(image_tag('pin.png'),addpin_path(:pin_id=>p.id))
                                    %>

                              <%= link_to(image_tag('like.png'),likes_path(:like=>{"pin_id"=>p.id}), :method => :post)
                                    %>
                              <%= image_tag p.source%>
                              <%=p.description%>
                              </div>
                        <% end %>
                  <% end %>
            <% end %>
      <% end %>





</div>
<script>
var $container = $('#container');
$container.imagesLoaded(function(){
  $container.masonry({
    itemSelector : '.item',
      columnWidth : 420
  });
});
</script>

</ul>

FinalProject/app/views/users/index.html.erb
<h1>Listing users</h1>

<table class="table table-striped table-hover">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Gender</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.gender %></td>
    <% if signed_in? %>
    <td><%= link_to 'Show', user , class: 'btn btn-primary'%></td>
    <td><%= link_to 'Edit', edit_user_path(user), class: 'btn btn-warning' %></td>
    <td><%= link_to 'Destroy', user, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>

    <td><%= link_to "Add Friend", follows_path(:follower_id => user), class: 'btn btn-success', :method => :post %> </td>
    <%end%>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path, class: 'btn' %>

FinalProject/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

FinalProject/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Gender:</b>
  <%= @user.gender %>
</p>
<div class="navbar navbar-text">
  <div class="navbar-inner containercolor">
    <div class="container">
    <ul class="nav">

      <li><a href="#" id="board-toggle"> board</a></li>
      <li><a href="#" id="pin-toggle"> pin </a></li>
      <li><a href="#" id="like-toggle"> like </a></li>
      <li><a href="#" id="following-toggle"> following </a></li>
      <li><a href="#" id="follower-toggle"> follower </a></li>
    </ul>
    </div>
  </div>
</div>
<div class ="field" id="board">

  <% if @boards.present? %>
    <h2>Boards: </h2>
      <ul>
        <% @boards.each do |b| %>
          <li> <%= link_to b.name, user_board_path(@user, b) %>
            <%if current_user == @user%>
            (<%= link_to "remove", b, :method => :delete %>)
            <%end%>
          </li>
        <% end %>
      </ul>
  <% else %>
	 You do not have a board yet, create one?
  <% end %>
  <% if current_user.name == @user.name %>
    <%= link_to 'New Board', new_board_path, class: 'btn' %>
    <%end%>
</div>

<div class = "field" id= "pin">
  <% if @pins.present? %>
    <h2> Pins: </h2>
      <ul>
        <% @pins.each do |p| %>
        <li> <%= link_to p.description, user_pin_path(@user, p) %>
          <%if current_user == @user%>
          (<%= link_to "remove", p, :method => :delete %>)
          <%end%>
        </li>
        <% end %>
      </ul>
  <% else %>
    <p> You do not have a pin yet, create one? </p>
  <% end %>
  <% if current_user.name == @user.name %>
    <%= link_to 'New Pin', new_pin_path, class: 'btn' %>
  <% end %>
</div>


<div class = "field" id= "like">
  <h2> Likes: </h2>
  <% if @likes.present? %>
      <ul>
        <% @likes.each do |p| %>
        <li> <%= link_to Pin.find(p.pin_id).description, user_pin_path(@user, Pin.find(p.pin_id)) %>
          <%if current_user == @user%>
          (<%= link_to "remove", p, :method => :delete %>)
          <%end%>
        </li>
        <% end %>
      </ul>
  <% else %>
    <p> do not have a like one yet </p>
  <% end %>
  <% if current_user.name == @user.name %>
    <%= link_to 'New Like', pins_path, class: 'btn' %>
  <% end %>
</div>







<div class = "field" id= "following">
  <h2> Following</h2>
    <% if @user.follows.present? %>
      <ul>
        <% for follow in @user.follows %>
          <li>
            <%=h follow.follower.name %>
            <%if current_user == @user%>
              (<%= link_to "remove", follow, :method => :delete %>)
              <%end%>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p> You do not follow anyone yet, find someone to follow? </p>
    <% end %>
    <% if current_user.name == @user.name %>
  <p><%= link_to "Find ppl to follow", addfriends_url(current_user), class: 'btn' %></p>
  <%end%>
</div>

<div class = "field" id= "follower">
  <h2> follower</h2>
    <ul>
      <% for user in @user.inverse_followers %>
      <li><%=h user.name %></li>
      <% end %>
    </ul>
</div>

<br></br>