FinalProject/config/routes.rb
FinalProject::Application.routes.draw do




  root to: "pages#login"

  resources :follow_boards
  resources :likes
  resources :follows

  resources :pins do
    resources :comments
  end

  resources :boards
  resources :categories
  resources :users do
  	resources :boards
  	resources :pins
  end



  get '/sessions/new' => 'sessions#new', as: 'new_session'
  post '/sessions' => 'sessions#create', as: 'sessions'
  delete '/sessions' => 'sessions#destroy', as: 'session'
  get 'users/:id/addfriends' => 'users#add_friends', as: 'addfriends'
  get 'users/:id/addpin' => 'users#add_pin', as: 'addpin'
  get 'login' => 'pages#login', as: 'login'
  get 'users/:id/homefeed' => 'users#home_feed', as: 'homefeed'

end

FinalProject/app/views/layouts/application.html.erb
<!DOCTYPE html>


<html lang="en">
<head>
  <meta charset="utf-8">
  <title>SocialSharing</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>



  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>

        <% if signed_in? %>
        <a class="brand" href="/users/<%= current_user.id %>/homefeed">SocialSharing</a>
        <% else %>
        <a class="brand" href="/login">SocialSharing</a>
        <% end %>

        <div class="nav-collapse">
          <ul class="nav">
            <% if signed_in? %>
            <li><%= link_to "add Friends", addfriends_url(current_user) %></li>
            <% else %>
            <li><%= link_to "Users", users_url %></li>
            <% end %>

            <li><%= link_to "Category", categories_url %></li>
            <% if signed_in? %>
              <li><%= link_to "Board", boards_url %></li>
              <li><%= link_to "Pin", pins_url %></li>
            <%end%>

            <% if signed_in? %>
              <li>
                <p><%= current_user.name %>.</p></li>
                <li><%= link_to "Sign Out", session_url, method: 'delete' %>
              </li>
            <% else %>
              <li><%= link_to "                    "%></li>
              <li><%= link_to "                    "%></li>

              <li><%= link_to "Sign In", new_session_url %> </li>  <li><%= link_to "Sign Up", new_user_url %></li>
            <% end %>



          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container">

    <% if notice.present? %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= notice %>
    </div>
    <% end %>
    <br>
    <br>
    <br>
    <br>
    <%= yield %>

    <hr>

    <footer>
      <p>&copy; Company 2012</p>
    </footer>

  </div>






</body>
</html>