starterGrill_Jiacheng/config/routes.rb
Aya::Application.routes.draw do
  root to: "pages#show"

  resources :foods
  resources :users
  resources :reservations

  get '/menu' => 'foods#menu', as: 'menu'
  get '/location' => 'locations#show', as:'location'
  get '/sessions/new' => 'sessions#new', as: 'new_session'
  post '/sessions' => 'sessions#create', as: 'sessions'
  delete '/sessions' => 'sessions#destroy', as: 'session'
  get '/pages' => 'pages#show', as: 'login'
  get '/help' => 'pages#help', as:'help'


end

starterGrill_Jiacheng/app/models/food.rb
class Food < ActiveRecord::Base
  attr_accessible :description, :name, :price, :food_type
end

starterGrill_Jiacheng/app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @foods }
    end
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
    @food = Food.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @food }
    end
  end

  # GET /foods/new
  # GET /foods/new.json
  def new
    @food = Food.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @food }
    end
  end

  # GET /foods/1/edit
  def edit
    @food = Food.find(params[:id])
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(params[:food])

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render json: @food, status: :created, location: @food }
      else
        format.html { render action: "new" }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /foods/1
  # PUT /foods/1.json
  def update
    @food = Food.find(params[:id])

    respond_to do |format|
      if @food.update_attributes(params[:food])
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food = Food.find(params[:id])
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url }
      format.json { head :no_content }
    end
  end

  def menu
    @starters = Food.where(:food_type => :starters)
    @entrees = Food.where(:food_type => :entrees)
    @drinks = Food.where(:food_type => :drinks)
    @desserts = Food.where(:food_type => :desserts)
  end

end

starterGrill_Jiacheng/app/helpers/foods_helper.rb
module FoodsHelper
end

starterGrill_Jiacheng/app/views/foods/_form.html.erb
<%= form_for(@food) do |f| %>
  <% if @food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% @food.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :food_type %><br />
    <%= f.text_field :food_type %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

starterGrill_Jiacheng/app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render 'form' %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

starterGrill_Jiacheng/app/views/foods/index.html.erb
<h1>Listing foods</h1>

<table class="table table-striped table-hover">
  <tr>
    <th>Name</th>
    <th>Type</th>
    <th>Price</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @foods.each do |food| %>
  <tr>
    <td><%= food.name %></td>
    <td><%= food.food_type %></td>
    <td><%= food.price %></td>
    <td><%= food.description %></td>
    <td><%= link_to 'Show', food %></td>
    <td><%= link_to 'Edit', edit_food_path(food) %></td>
    <td><%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Food', new_food_path %>

starterGrill_Jiacheng/app/views/foods/menu.html.erb
<h1>Menu</h1>

<ul>
  <li>
    Starters
    <ul>
      <% @starters.each do |s| %>
      <li> $<%= s.price %>  <%= s.name %> <br /> <%= s.description%></li> 
      <% end %>
    </ul>
  </li>
  
  <li>
    Entrees
    <ul>
      <% @entrees.each do |s| %>
      <li> $<%= s.price %>  <%= s.name %> <br /> <%= s.description%></li> 
      <% end %>
    </ul>
  </li>

   <li>
    Drinks
    <ul>
      <% @drinks.each do |s| %>
      <li> $<%= s.price %>  <%= s.name %> <br /> <%= s.description%></li> 
      <% end %>
    </ul>
  </li>

   <li>
    Desserts
    <ul>
      <% @desserts.each do |s| %>
      <li> $<%= s.price %>  <%= s.name %> <br /> <%= s.description%></li> 
      <% end %>
    </ul>
  </li>

</ul>

starterGrill_Jiacheng/app/views/foods/new.html.erb
<h1>New food</h1>

<%= render 'form' %>

<%= link_to 'Back', foods_path %>

starterGrill_Jiacheng/app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @food.name %>
</p>

<p>
  <b>Type:</b>
  <%= @food.food_type %>
</p>

<p>
  <b>Price:</b>
  <%= @food.price %>
</p>

<p>
  <b>Description:</b>
  <%= @food.description %>
</p>


<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>